// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFcJ2hpv7ZVvTBIG5RopNwcPDfyV9d_Vk',
    appId: '1:159080394055:web:b5a96bd9a4de9ffd4f7062',
    messagingSenderId: '159080394055',
    projectId: 'rental-system-6d494',
    authDomain: 'rental-system-6d494.firebaseapp.com',
    storageBucket: 'rental-system-6d494.appspot.com',
    measurementId: 'G-TB4N989MYE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2A3sDOAZnVttfYrmG7cJ1OfpDI4F6a_s',
    appId: '1:159080394055:android:49ca7ce1377b8ced4f7062',
    messagingSenderId: '159080394055',
    projectId: 'rental-system-6d494',
    storageBucket: 'rental-system-6d494.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOVVbtnzxjBbuVeRDrH_yQbfzj4xmKAXg',
    appId: '1:159080394055:ios:4d0550a0414d13be4f7062',
    messagingSenderId: '159080394055',
    projectId: 'rental-system-6d494',
    storageBucket: 'rental-system-6d494.appspot.com',
    iosBundleId: 'com.example.rental',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOVVbtnzxjBbuVeRDrH_yQbfzj4xmKAXg',
    appId: '1:159080394055:ios:5848985fbf157d3e4f7062',
    messagingSenderId: '159080394055',
    projectId: 'rental-system-6d494',
    storageBucket: 'rental-system-6d494.appspot.com',
    iosBundleId: 'com.example.rental.RunnerTests',
  );
}
