// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRl6h0S9OqsQGD0gmB4cSfzTpmwcaD0sk',
    appId: '1:293054246435:web:206b14c942d4db02354b96',
    messagingSenderId: '293054246435',
    projectId: 'rental-c49d0',
    authDomain: 'rental-c49d0.firebaseapp.com',
    storageBucket: 'rental-c49d0.firebasestorage.app',
    measurementId: 'G-K9EWQBNWYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZwSPkfMyGrdMx659_vraZrJAXDKXhKZs',
    appId: '1:293054246435:android:95ac6f32b8c4d1a2354b96',
    messagingSenderId: '293054246435',
    projectId: 'rental-c49d0',
    storageBucket: 'rental-c49d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4KIehEsZl95WZu8ezd3eO9K8xgawlFs8',
    appId: '1:293054246435:ios:c0ff4121ac08662c354b96',
    messagingSenderId: '293054246435',
    projectId: 'rental-c49d0',
    storageBucket: 'rental-c49d0.firebasestorage.app',
    iosBundleId: 'com.example.rental',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4KIehEsZl95WZu8ezd3eO9K8xgawlFs8',
    appId: '1:293054246435:ios:c0ff4121ac08662c354b96',
    messagingSenderId: '293054246435',
    projectId: 'rental-c49d0',
    storageBucket: 'rental-c49d0.firebasestorage.app',
    iosBundleId: 'com.example.rental',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRl6h0S9OqsQGD0gmB4cSfzTpmwcaD0sk',
    appId: '1:293054246435:web:d6a093affe9dea78354b96',
    messagingSenderId: '293054246435',
    projectId: 'rental-c49d0',
    authDomain: 'rental-c49d0.firebaseapp.com',
    storageBucket: 'rental-c49d0.firebasestorage.app',
    measurementId: 'G-TFNSB6ZQ96',
  );
}
